language: ruby
rvm:
- 2.2.2
cache: bundler
script:
- bundle exec rake
- bundle exec rubocop
after_success:
- bash bin/deploy ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
env:
  global:
  - secure: H+dXDCUZ3+yK823uzdnrb3tQNtk9PoBJEx9Gbr2pv3VSJtzWyVwDhap1eT1Mk91Aj+y7H4I/DBG78nncC5EbfzBzNJr69ulRZ2eDfL6d5z5YthDJBZcESYt6rKss0I7Vnh9GbrM5+KfhcxKdIt0jeCagc2LffCaAlUv8jeRgewejgLPX7hYZBglFgATud6sI5crOtqzqR8U13lJFrboNYP0rmtX2P2JaNu0x7IXnLt8UmREyxUwFGwS1zdcNto6YNpLLqLptkIfK9vY3+2ceIUOlLTYyJFlJVIS/Dgg4TM5E+N12NwSPca6EEBR5LInwSJjTHSshLSndEChw23FFAqhcGgGon1G7BeyRNp0Eh3QQKowu0SVTtaD85Ud8QKEsuAivb+xrrhp05UG2QhblQ97e0VkgT8KuC2LKI436cFH90uW1HZt+5EF2Fwezp1R3z9d0z/KnW7LL+5DaNU06Bqk0grTot5hwex2qB+2AjjHIb9DuJ83kdgjXouo972u+AQgTXOFRqyJ4+Q1MtgyC7JxMjm6SMBPaz2H2cCT5Urr4Izp2bAri55AQI33IHHcYpgLQUnk2aeg374LR6u6gb3Aeq0Xw9GvbqjxDQaZsRd7OVxbQCRqsBSi5DXxOemVVaSwnB9s5jDRfew015XnoTeu7UJB7MNsQ1+MiLNVofgg=
  - secure: d145m8q9c0RNfbLF2TZHZPRDqJ+9PeM9cO5DY+M7GHahJEz+/9eZEZ+vUEITI8rgpbHOFM3c20gMNs7kMOpXDJ/G7TnY5IIsPrmzDBK5Fr9OGQ5XMOCqMC+Y18ZqN/EtR+9mYNK2/v1DyyPHT83Wnc8yBcfxn8v8HxQyi4bIVId7N3S39nJqOb/cgyoBKENrsPwMGctb18hFlSEDzUAYr36+9IWw1cNazM3EetAbmLR2UMsyihAGJ2GkAK2283XF01fA5fM7/cJB/rg8y3zHs+2/OjhfEfB1jDu4VpSALudLudOVtYB0hKc0RnCQf0X7SBlbw6jTlvvlm3POq9HPZD89hSgQD1wUfWCyws/Vdn1ecMzDjwAthH9P5sAOCqVJu5dWJlId3tx2bQaCwR1YUwsrtpHhADISl0N5297avITPsKV2z9k/hdLkGMEcQ8a9dcY8Cjr3BUktQJ5SlSQnmvq7t+bVkXnZp8ir2mFLYhyANTzJ+rVC/4XL+kZfUy1S/kOqSdezNRk8RMBsmEqIuzxy69lRj1Z3Cz5hxG6axO9QAs/Ik/N40xwr/PlYSwgRc1aFLOXr+A1N14hX4W+GjT9VmQlWV3Ido+a5JHs5KNwS0i1uAgf6LFga8QIv1meiT1sUpVAPnDpFongd1VVuYWyM49Q7ic6VUf2sUuS63Uw=
